theme: minima

title: Learning GitHub Blog
author: Dylan Maclean
email: dylan@macleanvisual.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just a designer, standing in front a code editor, asking it to not completely blow up.

# social links
twitter_username: dylanjmaclean
github_username:  dylanjmaclean

show_excerpts: true # set to false to remove excerpts on the homepage
